### ISSUE TITLE
 Vue: Type  DirectusCollections  does not satisfy the constraint  TypeMap . Index signature for type 'string' is missing in type 'DirectusCollections'.

### ISSUE THREAD

**Issue by notflip** [directus-community/agency-os#14]
https://github.com/notflip/agency-os/blob/031451669d926c9dea6419d8ad9d9ca6073af670/modules/directus-build.ts#L22

After a fresh install, I'm getting the following error

```
Vue: Type  DirectusCollections  does not satisfy the constraint  TypeMap . Index signature for type 'string' is missing in type 'DirectusCollections'.
```

![Screenshot 2023-07-26 at 14 34 36](https://github.com/directus-community/agency-os/assets/4146384/46d26b8b-d4aa-49ea-a5b8-429d52c61411)

**Comment by bryantgillespie** [comment]
We'll sort this one out when we implement the new version of the Directus SDK.
