### ISSUE TITLE
"Unexpected Error" for Content > Project

### ISSUE THREAD

**Issue by notflip** [directus-community/agency-os#15]
Using a default blank installation, I'm getting the following error when visiting a content single page

![Screenshot 2023-07-26 at 14 46 01](https://github.com/directus-community/agency-os/assets/4146384/f42fa900-33f7-4234-9380-ee6db4da75bf)

**Comment by bryantgillespie** [comment]
Hmmm – curious what database are you using?

**Comment by notflip** [comment]
MySQL, hosted on Cleavr (default one-click install)

**Comment by bryantgillespie** [comment]
> MySQL, hosted on Cleavr (default one-click install)

Got it. Yeah we have had some reports of issues with using the template-cli and MySQL as the database. Haven't had the time to investigate fully yet. But PostgreSQL and SQLite are confirmed to work.

**Comment by notflip** [comment]
@bryantgillespie Thanks! I'll use SQLite for my next project for now.
