### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by rowild** [directus-community/agency-os#23]
My local setup throws CORS errors (see attachment).  According to https://nitro.unjs.io/config#routes I tried to added

```json
export default defineNuxtConfig ({ 
  routeRules: {
    '/**': { cors: true, headers: { 'access-control-allow-methods': 'GET' } },
  }
})
```

but to no avail.

I also worked through solutions posted in these articles:
https://mookypoo.medium.com/nuxt-js-how-to-handle-cors-error-a4c5022611d0
https://github.com/nuxt/nuxt/issues/14598
without success.

Any idea how to solve this problem?

**Comment by bryantgillespie** [comment]
If it's your local setup - you might want to enable CORS inside your Directus config - set `CORS_ENABLED` to `true`

![ScreenShot 2023-09-13 at 16 38 10@2x](https://github.com/directus-community/agency-os/assets/23302570/dcd875a7-dea2-48a6-b777-f44f6ecd06da)

**Comment by rowild** [comment]
Ah - I have to adjust the Directus part in this case! Thank you! Now navigating the page is working. 

However, images that come with the package still don't load. Inspecting the File Library I see that all images are visible only in the root folder, but none is in any subfolder (e.g. team). 
Uploading and implementing my own images works.l 

Could this be a permission problem? 

(Also I would like to mention that the schema is not what one know from Directus. Alls fields seem to be in alphabetical order, meaning that "sort" and "status" and "uploaded by" etc are at the end of the field lists...)

**Comment by rowild** [comment]
@bryantgillespie My setup is still full of errors, and I don't know why. I mean to have installed everything properly (using yarn on the repo with no changes). 

It starts out with the fact that "localhost:3000" does not open, instead the json of a 500 error message is shown. Weird is, that when I open "localhost:300/team" and click on the logo there (which leads me to "localhost:3000/"), the browser DOES show a site (but definitely not all, there are things missing). – I actually assume this has to do with the before mentioned fact that existing images (images that came with the package on installation) don't show in the frontend, because that 500 message occurs in a file called `LogoCloud.vue` which seems to use logo image files...

Second: "nitro" claims "I do not have access to this." and mentions "url: '/items/chat_config'," in it's json error output (attached). It seems to be related to the chat module, which is called in a composable via `... await $directus.items('chat_config')`, but I don't know where "items/chat_config" is in Directus.

Third: There are lots of Typescript errors in VSCode (see attachment). TS is installed via the package.json, but I also have a locally installed one (global). I can tell VSCode which one to use, but that won't make any difference.

And previousely I already mentioned that the images that come with the repo won't load. Images, that I add and use in content elements, work fine, though.

After 3 days I have to ask, maybe my error is a dead simple one which I just don't see. Do you happen to have any idea?


[errors.txt](https://github.com/directus-community/agency-os/files/12641138/errors.txt)

![1-error-on-home-route](https://github.com/directus-community/agency-os/assets/213803/56eafb10-9e1a-407f-ab3a-f0408c2d79ca)
![2-no-item-chat-config](https://github.com/directus-community/agency-os/assets/213803/ef60bfd2-4a94-457f-b40b-d8f00b0c73f6)
![3-typescript-errors-in-vscode](https://github.com/directus-community/agency-os/assets/213803/01c0f7cb-cbdf-480d-8a2a-3635c2ec1ad3)

**Comment by rowild** [comment]
Any insights on these problems?
