### ISSUE TITLE
Error when applying template

### ISSUE THREAD

**Issue by RamaHerbin** [directus-community/agency-os#24]
**Environnement**
Directus version 10.6.0 SQLite version running on localhost
Macos 12.6.1

**Description**
Hello there,

I'm experiencing errors while using the `npx directus-template-cli apply` command.
<img width="925" alt="Screenshot 2023-09-19 at 10 00 48" src="https://github.com/directus-community/agency-os/assets/41597427/11aaf555-e168-4e02-9595-b35220bedabf">

This result in incomplete/breaking form 
<img width="1067" alt="Screenshot 2023-09-19 at 13 58 08" src="https://github.com/directus-community/agency-os/assets/41597427/42597c76-c47b-40f0-ba89-ea3166d943b2">

**Comment by alexvdvalk** [comment]
You may just need to refresh your browser again once the preset is applied.

The preset error has been resolved: https://github.com/directus-community/directus-template-cli/pull/32

**Comment by RamaHerbin** [comment]
I just re-installed completety a new directus project and reapplied the template and now everything looks to work fine. 
I don't understand what I've done wrong in the previous attempt 🤔
Thanks for your quick response !

But now I have another question, I reviewed the `block_video` component and I don't understand how the `type` conditional field works. Usually when I want to have a field that changes dynamically according to an input value of a radio button, I add a condition to the field that depends on the value, and if the value corresponds I show and hide fields accordingly. But in the case of the `type` file in block_video I don't see any condition.
So I'm wondering how the dynamic field is working ?

<img width="628" alt="Screenshot 2023-09-25 at 11 04 52" src="https://github.com/directus-community/agency-os/assets/41597427/0052eea8-487f-40b9-8642-2c35d3750a22">

**Comment by laurnts** [comment]
For people having an error while applying template using
```
npx directus-template-cli apply
```
It doesn't work with MySQL or MariaDB as stated here
https://github.com/directus-community/directus-template-cli
