### ISSUE TITLE
Link error?

### ISSUE THREAD

**Issue by ijpatricio** [directus-community/agency-os#30]
Hey, Directus team!!

I think I found a wrong link.
Check the image. This is pointing to deploying a template in Railway.

![image](https://github.com/directus-community/agency-os/assets/26031459/e3e79c7a-94ac-4213-9f10-813eabbb60f5)

Congrats, this looks amazing!

**Comment by ijpatricio** [comment]
This is in README.md

**Comment by bryantgillespie** [comment]
Yup thanks for pointing that out.

Got it fixed!
