### ISSUE TITLE
Fetch the data from the server side instead of the client?

### ISSUE THREAD

**Issue by daver987** [directus-community/agency-os#31]
I've been exploring Directus for self-hosting scenarios over the past few weeks. While I've found it to be a powerful solution, I faced persistent CORS issues that ultimately led me to abandon my first project due to time constraints.

To overcome this, I've experimented with server-side data fetching, bypassing the SDK in favor of direct REST API calls. This effectively uses server routes as a proxy, eliminating the CORS issues I encountered. When deployed via Docker, this setup works seamlessly.

Given these challenges, I'm wondering if server-side data fetching is something you're considering adding to this template. It could provide a smoother development experience for those looking to self-host Directus.

I'd be more than willing to contribute to this feature in my spare time if it aligns with your roadmap.

**Comment by bryantgillespie** [comment]
> I've been exploring Directus for self-hosting scenarios over the past few weeks. While I've found it to be a powerful solution, I faced persistent CORS issues that ultimately led me to abandon my first project due to time constraints.

Did you have a look at the CORS section of the Directus config?
https://docs.directus.io/self-hosted/config-options.html#cors

On local dev, I often set CORS_ENABLED to `true` so there are no issues to contend with locally.

Once I've got the config correct, I've never had an issue with CORS and Directus.

---

If you'd prefer not to use the SDK in your project, it wouldn't be a ton of work to create a server route for your proxy and adjust all the data fetching calls from useAsyncData to useFetch. 

As of now - no explicit plans to include that as part of this template though.

**Comment by daver987** [comment]
Thank you for the reply.  I did set the CORS_ENABLED to true but still no luck. I just took your directus server function and made it a composable and moved all the client side fetching to server routes and it fixed the cors errors.  It's a great template by the way.  I love all the new updates!
