### ISSUE TITLE
A bunch of errors when trying to run this system

### ISSUE THREAD

**Issue by cve** [directus-community/agency-os#40]
Hi, 

First of all, thank you for share this interesting system.

I have Windows with WSL2 and all commands (and repo) are in WSL.

I clone the repo and open it in my IDE. 

I moved to `.directus` dir and type `docker compose up`, in the console I see that:

![image](https://github.com/directus-community/agency-os/assets/594384/dda7ee9b-7937-4f89-a245-33e8123f198b)

I go to http://localhost:8055 and  I can successfully login. So I create a token for admin user.

On another terminal window I type `npx directus-template-cli@latest apply` and paste my admin token. I choose Headless CMS - Website as template. Now I see a lot of errors like that: 

![image](https://github.com/directus-community/agency-os/assets/594384/a0af915d-8533-4d7d-b30f-63cb9067a1b5)

but at the end it says:

![image](https://github.com/directus-community/agency-os/assets/594384/10e8a5c8-4c2c-4ae5-9caf-29304007c154)

So, I copy `.env.example` to `.env`, I update env vars.

I run `pnpm i` which installs all succesffully

i run `pnpm dev` and after few seconds I see that errors:

![image](https://github.com/directus-community/agency-os/assets/594384/b3e6a7ab-ab86-445d-a05f-09aec2deef58)

I open `http://localhost:3000` and I see that:

![image](https://github.com/directus-community/agency-os/assets/594384/eb5ff22c-ed67-4fd9-b76b-c626345d1d5d)

But in directus it looks like I have home page:

![image](https://github.com/directus-community/agency-os/assets/594384/88901540-9233-4070-af66-829b32f5776f)

**Comment by bryantgillespie** [comment]
1. Try to grab the latest files from the repo as I removed the Directus extension that was bundled with this.

2. Make sure you follow instructions explicitly. You stated that you applied the "Headless CMS - Website" template. You have to apply the "AgencyOS" template from the template CLI in order for it to work.
