### ISSUE TITLE
invalid admin token on localhost

### ISSUE THREAD

**Issue by musfandi** [directus-community/agency-os#45]
What type of template would you like to apply? 
Official templates
Select a template. AgencyOS
You selected AgencyOS
------------------
What is your Directus URL?: http://localhost/
What is your Directus Admin Token?: Yr0rolr_BVtSB_c0UBzpnyumHd08di2s
 »   Warning: Invalid token
What is your Directus Admin Token?: 
![Screenshot 2023-11-14 112114](https://github.com/directus-community/agency-os/assets/4033246/fda01221-27d7-48ad-9667-6bf4452596bd)

**Comment by kinged007** [comment]
Did you save the user profile before trying to connect? You need to save new generated tokens before you can use it.
Is Directus really on port 80 on localhost? Not 8055 or something else?

**Comment by bryantgillespie** [comment]
A few things...
1) I realize it's your localhost but it's still not good practice to post actual tokens on the interwebs.

2) You need to make sure you save the user after you generate the token or else it will not work.

3) As @kinged007 mentions unless you've configured it differently Directus defaults to port 8055 so your url probably needs to be changed to something like `http://localhost:8055`

**Comment by musfandi** [comment]
thanks... work with http://localhost:8055

> A few things...
> 
> 1. I realize it's your localhost but it's still not good practice to post actual tokens on the interwebs.
> 2. You need to make sure you save the user after you generate the token or else it will not work.
> 3. As @kinged007 mentions unless you've configured it differently Directus defaults to port 8055 so your url probably needs to be changed to something like `http://localhost:8055`

**Comment by Pachat** [comment]
I had the same problem of invalid token on localhost. But the cause was different.
I finally could install AgencyOS on my laptop modifying the HOST
```
# IP or host the API listens on ["0.0.0.0"]
# HOST="0.0.0.0"
HOST="localhost"

# The port Directus will run on [8083]
PORT=8083
```
BTW, I have a side question: 
If improvements are made by Directus to the template, how can I integrate them on a customized AgencyOS?

Thank you very much Directus for this template is a life-saving!

**Comment by bryantgillespie** [comment]
> If improvements are made by Directus to the template, how can I'll ba able to integrate them later on a customized AgencyOS?

Because this is setup a template repo - I think you'd be applying any updates manually.

You can always fork the repo instead and then you'd be able to pull any of the latest changes.

**Comment by Pachat** [comment]
Thank you for your response
Will the pull request preserve our changes? In other words is it possible to have a kind of "child template"?

**Comment by bryantgillespie** [comment]
You'd have to merge your changes with whatever changes were made her in the main repo. But it's possible.

We're using [Nuxt Layers](https://nuxt.com/docs/getting-started/layers) to separate the portal and proposal logic from the regular website application. It's a really neat concept.

Down the road, I'd love to explore potentially wrapping AgencyOS up as an npm package that you could pull into your own Nuxt application and "overwrite" individual pages or components with your own.
