### ISSUE TITLE
'Column block' not working in frontend

### ISSUE THREAD

**Issue by JasperAorus** [directus-community/agency-os#48]
I am not sure if this is a bug, but it seems the 'column block' is not showing in the front-end. It is also not showing in the demo site of agencyOS, there should be a 'services' block on the home page below the 'form section', but it is not showing. Same if I add new Column blocks on a different page.

**Comment by bryantgillespie** [comment]
Thanks for pointing that out. Not sure exactly what caused it to break but will get it sorted!

**Comment by pascalvb** [comment]
The BlockType in PageBuilder got renamed from `block_columns` to `block_column` (singular vs plural).
I could provide a PR to revert this change (under the assumption this was not intentional)
