### ISSUE TITLE
Error: Invalid URL string on Cloudflare pages

### ISSUE THREAD

**Issue by drkNsubuga** [directus-community/agency-os#53]
# The issue
I intend to deploy the Nuxt frontend as SSR on **Cloudflare pages** but keep getting this error
```console
Failed to publish your Function. Got error: Uncaught TypeError: Invalid URL string.
```

## Build Settings
> **Build command:** `pnpm build`
**Build output directory:** `/dist`
**Build system version:** 2 (latest)
**Root directory:** /

**Environment variables:**
```env
DIRECTUS_URL=<directus_url>
DIRECTUS_SERVER_TOKEN=*****
SITE_URL=customdomain.com
NUXT_PUBLIC_SITE_URL=customdomain.com #Added this variable based on the nuxt.config.js
   ```
 ## Part of the log
 ```console
✨ Compiled Worker successfully
[redacted logs]
Success: Assets published!
Error: Failed to publish your Function. Got error: Uncaught TypeError: Invalid URL string. 
at functionsWorker-0.8365433674024725.js:7285:30 in w$6   at functionsWorker-0.8365433674024725.js:7447:10
```

### I also tried these build settings:
> **Build command**: `pnpm build`
**Build output directory**:` /.output/public `

but  the output folder could not be found.

> **Build command:** `pnpm build && pnpm start`

and encountered this error
```console
 > nuxt start
[error] Cannot find `nitro.json`. Did you run `nuxi build` first? Search path:
'/opt/buildhome/repo/server/.output/nitro.json',
'/opt/buildhome/repo/.output/nitro.json' ]
ELIFECYCLE  Command failed with exit code 1.
Failed: Error while executing user command. Exited with error code: 1
Failed: build command exited with code: 1
Failed: error occurred while running build command
```

**Comment by bryantgillespie** [comment]
I'm not sure exactly what's causing the issue here. I don't typically deploy through Cloudflare so I don't have much experience with it.

Have you tried adding `http://` or `https://` in front of your SITE_URL and NUXT_PUBLIC_SITE_URL env variables?

Maybe that's the invalid URL string it's referring to?

**Comment by drkNsubuga** [comment]
Hello @bryantgillespie 
Yes, I added both of them but got the same error. Strangely, the build is successful when I set the `build output folder` to the root folder `/` but the app shows a 404 browser error. Probably, it's a cloudflare specific issue
