### ISSUE TITLE
Issue Enabling Stripe Integration in Agency-OS with Stripe Webhook

### ISSUE THREAD

**Issue by omgitsjan** [directus-community/agency-os#55]
Hey, I am attempting to enable Stripe on my agency-os platform, but I've encountered a roadblock. The documentation doesn't specify which endpoint URL should be used. Before I can create a Stripe token, I need to specify a URL, but it's unclear where I can find this information.

So my questions are:
1. What is the correct endpoint URL to use for Stripe integration in agency-os?
2. Where in the documentation can I find this information, or is it missing entirely?

Thanks is advance!

**Comment by bryantgillespie** [comment]
I'm assuming your talking about the Stripe webhook URL but correct me if I'm wrong.

> What is the correct endpoint URL to use for Stripe integration in agency-os?

The URL for Stripe webhooks should look like this...
`{{your_url_for_frontend}}/api/stripe/webhooks`


> Where in the documentation can I find this information, or is it missing entirely?

Here's a solid video tutorial on it.
https://youtu.be/46vh-39maRM

Definitely need to add some documentation on it.

**Comment by omgitsjan** [comment]
Yes, exactly, I was referring to the Stripe webhook URL.

Perfect! I missed the tutorials on YouTube, that will definitely help. 

And thanks for your amazing work!
