### ISSUE TITLE
Custom page-builder block not showing prop items?

### ISSUE THREAD

**Issue by Loosie94** [directus-community/agency-os#57]
Hi guys,

I have build a custom block for the page-builder called "block_downloads".
This block has 3 fields: "id", "title" and "files". 
I have added this block to the pagebuilder call on the "[...permalink].vue" file.

So far so good. 
Only issue is that I don't see my field when trying to recieve them with defineProps.
I have already created a BlockDownloads type for this block, and already added my collection to the page_blocks collection field.

The existing blocks all have the data available in the "data" prop.
I just can't figure out why this is not working for my custom block.

Thanks in advance!

**Comment by Abdallah-Awwad** [comment]
That's a simple missing thing, but just making sure that you didn't forget it. 
Did you set the read public permission of that the block to all access in Directus itself?
![image](https://github.com/directus-community/agency-os/assets/129249191/e1870cb1-1e7f-4ca0-8838-fc9a0ea9425d)

**Comment by Loosie94** [comment]
@Abdallah-Awwad I feel like an idiot. That was the issue. Enabling them for the public role solves the issue. Many thanks! :)

**Comment by Loosie94** [comment]
@Abdallah-Awwad I feel like an idiot. That was the issue. Enabling them for the public role solves the issue. Many thanks! :)

**Comment by Abdallah-Awwad** [comment]
No worries, I felt the same when @Natetronn reminded me about it too, so, it happens 😅
Glad it worked though.
