### ISSUE TITLE
pnpm build - Memory requirements

### ISSUE THREAD

**Issue by efrazier** [directus-community/agency-os#61]
What should I expect? I found that doing the build failed with the good old heap out of memory error.  I had to increase the size of my AWS instance again, because this was for real. I ended up peaking on the build with about 6G in use and all was well. 

5.15.0-1051-aws #56~20.04.1-Ubuntu SMP Tue Nov 28 15:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

node -v v20.10.0

npm -v 10.2.3

pnpm -v 8.13.1

env | grep NODE
NODE_OPTIONS=--max-old-space-size=32768

So this worked, but I am wondering why I need a large instance just to build an Agency website??

Also running  pnpm start tells me to run ./server/index.mjs, 

![image](https://github.com/directus-community/agency-os/assets/3696386/6671a359-7c0c-42e0-a39b-89c37de44f37)

but that is actually located here

:/home/directus/team-osb# node .output/server/index.mjs
Listening on http://[::]:3000

**Comment by bryantgillespie** [comment]
> Also running pnpm start tells me to run ./server/index.mjs,
> 
> image
> 
> but that is actually located here
> 
> :/home/directus/team-osb# node .output/server/index.mjs
> Listening on http://[::]:3000

When you're working locally `nuxt start` loads the .env file for you. In your production deployment, depending on your Nuxt preset and host - Vercel, Netlify, etc – that host will inject that .env file for you.

**Comment by bryantgillespie** [comment]
> What should I expect? I found that doing the build failed with the good old heap out of memory error. I had to increase the size of my AWS instance again, because this was for real. I ended up peaking on the build with about 6G in use and all was well.
> 
> 5.15.0-1051-aws https://github.com/directus-community/agency-os/pull/56~20.04.1-Ubuntu SMP Tue Nov 28 15:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> node -v v20.10.0
> 
> npm -v 10.2.3
> 
> pnpm -v 8.13.1
> 
> env | grep NODE
> NODE_OPTIONS=--max-old-space-size=32768


I believe the memory hogging is a combo of the older versions of Nuxt and the nuxt-og-image module.

Pushing an update soon that has updated dependencies that hopefully solve the problem.
